name: 🚀 Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.83.0
      - uses: taiga-family/ci/actions/setup/node@v1.83.0
      - run: npx nx build-gh-pages demo
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          branch: gh-pages
          folder: dist/demo
          silent: false
          clean: true

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
